### ISSUE TITLE
Krmfile for setters

### ISSUE THREAD

**Issue by blaggacao** [ContainerSolutions/trow#183]
Since you have excelent kustomize support, I'd like to bring to your attention the newst setters development upstream:

#### Manifest:
```yaml
# Krmfile
apiVersion: config.k8s.io/v1alpha1
kind: Krmfile
openAPI:
  definitions:
    io.k8s.cli.setters.namespace:
      description: namespace for the app
      type: string
      x-k8s-cli:
        setter:
          name: namespace
          value: default
          count: 1
```

#### Usage: (`# {"$openapi":"namespace"}`)
```yaml
namespace: "default" # {"$openapi":"namespace"}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../upstream
```

Now this field can be easily customized with `kustomize cfg set install/base namespace my-namespace` which get's recorded back as values into the Krmfile.

Caveat: files like [this path](https://github.com/ContainerSolutions/trow/blob/master/install/base/patch-validator-domain.yaml) must be in-lined into a valid GVK resource, but can be elided, on the other hand if that is wished.

See: 
```
Error: ../../upstream/base/patch-trow-arg.yaml: wrong Node Kind for  expected: MappingNode was SequenceNode: value: {- op: replace
  path: /spec/template/spec/containers/0/args/2
  value: newregistry.mydomain.com}
```
