### ISSUE TITLE
Not able to pull images from trow-registry. "unexpected commit digest"

### ISSUE THREAD

**Issue by Christian-Rau** [ContainerSolutions/trow#228]
I assume I must have missed the secret "cred" pod, so could someone please explain how to set the deployment API:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimistic-app
  namespace: notdefaultforsure
spec:
  selector:
    matchLabels:
      name: optimistic-backend
  template:
    metadata:
      labels:
        name: optimistic-backend
    spec:
      imagePulleSecrets:
        - name: trow-password   << what to add here?
      containers:
        - name: backend
          image: trow.optimistic.reg/simpleapp:latest
          ports:
            - containerPort: 80
```

I used the helm chart - but that's not ideal as I couldn´t figure out how to set a namespace. 
Edit: cleaned up a bit.
