### ISSUE TITLE
Failed to start Trow server: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

### ISSUE THREAD

**Issue by farlop** [ContainerSolutions/trow#35]
After following Standard Kubernetes Install instructions including:

- Deploying cert-manager (since it's a new cluster)
- Copying example-overlay folder and updating
    - Updating literals 'pass', 'docker-server', 'docker-username', 'docker-password' in kustomization.yaml
    - Updating patch-ingress-host
    - Updating patch-trow-args
- Creating namespace manually
- Creating PV manually (since it's a baremetal cluster)
- Creating DNS in server
- Applying files

I'm getting this error when checking at logs for trow-deploy

Any idea of what I'm missing?

**Comment by amouat** [comment]
I suspect it can't write to the file system (probably the PV).

At the very least it should give you a more informative error. I'll take a quick look tomorrow, but it might be difficult to recreate the problem as you have a bespoke system.

**Comment by farlop** [comment]
This is what my PersistentVolume looks like:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: trow-data
  labels:
    type: local
spec:  
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/trow-data"
```

**Comment by amouat** [comment]
Can you check you have the following in your deployment yaml:
```
securityContext:             
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
```

That should set things so that the volume can be read by the trow user (Trow no longer runs as root). If you still have problems, try changing the image to nginx, then exec into the container and see if you can create files on the volume as uid 999.
