### ISSUE TITLE
Ingress route paths needs routing to v2 as well

### ISSUE THREAD

**Issue by foggy-glasses** [ContainerSolutions/trow#87]
Something I missed to mention before. Post installation following the standard installation instructions, my nginx route paths had just one path to root as follows.

```
....
          - path: /
            backend:
                serviceName: trow-svc
                servicePort: 8000
...
```
However, when I attempted to login to my private registry, I got the below error.
```
masternode@masternode-VirtualBox:~/yml_files$ sudo docker login -u dt-onprem https://myregistry.mydomain.com/
Password:
Error response from daemon: Get https://myregistry.mydomain.com/v2/: dial tcp: lookup myregistry.mydomain.com: no such host

```
So I added one more route to point to v2 as below and then it succeeded..
```
....
          - path: /
            backend:
                serviceName: trow-svc
                servicePort: 8000
          - path: /v2
            backend:
                serviceName: trow-svc
                servicePort: 8000
...
```
I do have an annotation in my ingress to use regex. But apart from that there's not much difference. The instructions and example don't mention this additional path. Does anyone else has a similar issue?
